### ISSUE TITLE
Implementing Folder Structure

### ISSUE THREAD

**Issue by AsishRaju** [Canvasbird/canvasboard-backend#10]
Currently, all files that the user has is directly attached to the user, we want to implement a folder structure, 
**`user--will have-->folders--will have-->files`** 

This will help in keeping the file management clean, so eventually, CURD APIs for the folders are needed and modifying files relationship with the user.

**`files--will have a relationship with-->folders--will have a relationship with-->user`**

**Comment by AyonPal** [comment]
@AsishRaju as file upload and download both are already implemented, do we need to only create CURD api for folder only?

**Comment by AsishRaju** [comment]
@AyonPal  yes, also keeping the relationship in mind you gotta look out how files are uploaded as the can only exist inside folders
